version: "3.8"
services:
  mysql-db:
    container_name: "mysql-db"
    image: mysql:8.0.36
    environment:
      MYSQL_DATABASE: "GESTAO_HOSPITALAR_DB"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./scripts/:/docker-entrypoint-initdb.d
volumes:
  mysql:
